[book]
language = "en"
multilingual = false
src = "docs"
title = "Data Science Threat Intelligence"

[build]
build-dir = "docs/book"

[preprocessor.kroki-preprocessor]
command = "mdbook-kroki-preprocessor"
