[depot.x86_64-linux.fetchzip.registry-General]
name = "registries/General"
sha256 = "sha256-XiJPSW9Lcl30viQ7GUThuBHr2TbgqidFp5h03oHReh0="
stripRoot = false
url = "https://pkg.julialang.org/registry/23338594-aafe-5451-b93e-139f81909106/85a45ae70f27086616b6426506b47df3aab28c13#registry.tar.gz"

[depot.x86_64-linux.fetchgit.package-PooledArrays]
name = "packages/PooledArrays/DXlaI"
sha256 = "sha256-z4N2P6XVMriTd7AfKGNBQdAoPp4OShZT3ogxZA1pYDw="
rev = "a6062fe4063cdafe78f4a0a81cfffb89721b30e7"
url = "https://github.com/JuliaData/PooledArrays.jl.git"

[depot.x86_64-linux.fetchgit.package-IteratorInterfaceExtensions]
name = "packages/IteratorInterfaceExtensions/NZdaj"
sha256 = "sha256-Cah708wvvD0Vxm63YZK1k7399B3rfONfckhJ2IJXl+o="
rev = "a3f24677c21f5bbe9d2a714f95dcd58337fb2856"
url = "https://github.com/queryverse/IteratorInterfaceExtensions.jl.git"

[depot.x86_64-linux.fetchgit.package-Formatting]
name = "packages/Formatting/BwWBf"
sha256 = "sha256-sOaNM7LcJ9iqYYos6TQHOA9I2OwinLIWGjmH4mvCQ1U="
rev = "8339d61043228fdd3eb658d86c926cb282ae72a8"
url = "https://github.com/JuliaIO/Formatting.jl.git"

[depot.x86_64-linux.fetchgit.package-PrettyTables]
name = "packages/PrettyTables/xfzM5"
sha256 = "sha256-ZVNZpai4qq+0LIoIs+OA32wLGIa45GOKNPBh0DAAaEo="
rev = "d8ed354439950b34ab04ff8f3dfd49e11bc6c94b"
url = "https://github.com/ronisbr/PrettyTables.jl.git"

[depot.x86_64-linux.fetchgit.package-DataFrames]
name = "packages/DataFrames/KKiZW"
sha256 = "sha256-JGbC52eDpaNTTB9OXDRqTRqxGVHTLz3uXvKlhe6Lt1c="
rev = "0f44494fe4271cc966ac4fea524111bef63ba86c"
url = "https://github.com/JuliaData/DataFrames.jl.git"

[depot.x86_64-linux.fetchgit.package-DataValueInterfaces]
name = "packages/DataValueInterfaces/0j6Kp"
sha256 = "sha256-6FE9U6PRIY16wTNkW1kXlLDAT0eznWe6NSVJebCRXDw="
rev = "bfc1187b79289637fa0ef6d4436ebdfe6905cbd6"
url = "https://github.com/queryverse/DataValueInterfaces.jl.git"

[depot.x86_64-linux.fetchgit.package-Tables]
name = "packages/Tables/T7rHm"
sha256 = "sha256-ZpQ3m7gJNykqdbJ4XbRSP3uCfTCQ1joddhNuaWFphP4="
rev = "c79322d36826aa2f4fd8ecfa96ddb47b174ac78d"
url = "https://github.com/JuliaData/Tables.jl.git"

[depot.x86_64-linux.fetchgit.package-Missings]
name = "packages/Missings/r1STI"
sha256 = "sha256-pSkjsjW9j6xGLfqeykF+W4NgSTsnSDKglxUqWmoOiMw="
rev = "bf210ce90b6c9eed32d25dbcae1ebc565df2687f"
url = "https://github.com/JuliaData/Missings.jl.git"

[depot.x86_64-linux.fetchgit.package-Compat]
name = "packages/Compat/ysINt"
sha256 = "sha256-K/iF7LTTuhsOxFeQO1h87wxmAVS5sWm30z/ZuLb5+Kg="
rev = "aaabba4ce1b7f8a9b34c015053d3b1edf60fa49c"
url = "https://github.com/JuliaLang/Compat.jl.git"

[depot.x86_64-linux.fetchgit.package-StringManipulation]
name = "packages/StringManipulation/wxRU4"
sha256 = "sha256-CAdhzjRj1NvWeGzo58Hnt8GgVM85zyCN6UJLLydEWpc="
rev = "46da2434b41f41ac3594ee9816ce5541c6096123"
url = "https://github.com/ronisbr/StringManipulation.jl.git"

[depot.x86_64-linux.fetchgit.package-InvertedIndices]
name = "packages/InvertedIndices/Zdhhq"
sha256 = "sha256-OuKnTAwd040lFfLnapSrnyA2uBggWvsb+NOR6H8j1Zc="
rev = "bee5f1ef5bf65df56bdd2e40447590b272a5471f"
url = "https://github.com/JuliaData/InvertedIndices.jl.git"

[depot.x86_64-linux.fetchgit.package-LaTeXStrings]
name = "packages/LaTeXStrings/pJ7vn"
sha256 = "sha256-nBcJ8H3Y4KLiWvOLTMkZSuFNAT76mjx1ebgmxUy6MkY="
rev = "f2355693d6778a178ade15952b7ac47a4ff97996"
url = "https://github.com/stevengj/LaTeXStrings.jl.git"

[depot.x86_64-linux.fetchgit.package-ExproniconLite]
name = "packages/ExproniconLite/ifLkn"
sha256 = "sha256-0nMfANL3RfS34Cevqut6NgSSGpYBmYrj4QdhX9s/fZ8="
rev = "2321c9c5a07c2658484dacf8e68e3cd8e2470d5d"
url = "https://github.com/Roger-luo/ExproniconLite.jl.git"

[depot.x86_64-linux.fetchgit.package-OrderedCollections]
name = "packages/OrderedCollections/PRayh"
sha256 = "sha256-jkM6lAXu8+UnsrzYeCI4GqT/YpvRBxB+xvejO3dlXUk="
rev = "85f8e6578bf1f9ee0d11e7bb1b1456435479d47c"
url = "https://github.com/JuliaCollections/OrderedCollections.jl.git"

[depot.x86_64-linux.fetchgit.package-SortingAlgorithms]
name = "packages/SortingAlgorithms/n1AWW"
sha256 = "sha256-yCypup4k/Q/5ydCGRFcBuIyoOJPnqpH+LWmdL56dmSo="
rev = "a4ada03f999bd01b3a25dcaa30b2d929fe537e00"
url = "https://github.com/JuliaCollections/SortingAlgorithms.jl.git"

[depot.x86_64-linux.fetchgit.package-RelocatableFolders]
name = "packages/RelocatableFolders/xuLyx"
sha256 = "sha256-E3fVbrOdCYpVkur0qvpUgfM9hHKCHdQ0S+OVTDL0KnE="
rev = "90bc7a7c96410424509e4263e277e43250c05691"
url = "https://github.com/JuliaPackaging/RelocatableFolders.jl.git"

[depot.x86_64-linux.fetchgit.package-Crayons]
name = "packages/Crayons/u3AH8"
sha256 = "sha256-7fZ3X+fB9nBf+Ly45nlRb5ZEFEoZ5kPZXZRTdgVYy20="
rev = "249fe38abf76d48563e2f4556bebd215aa317e15"
url = "https://github.com/KristofferC/Crayons.jl.git"

[depot.x86_64-linux.fetchgit.package-Reexport]
name = "packages/Reexport/OxbHO"
sha256 = "sha256-jle1YBDjUkczbAjSbp49wmgo9ucVVV5YacwG4AwuzkY="
rev = "45e428421666073eab6f2da5c9d310d99bb12f9b"
url = "https://github.com/simonster/Reexport.jl.git"

[depot.x86_64-linux.fetchgit.package-SnoopPrecompile]
name = "packages/SnoopPrecompile/UWvXF"
sha256 = "sha256-MP1NnOIjjyqkYLCATEn+E4idIeOMwBA/ONE4my23eQY="
rev = "f604441450a3c0569830946e5b33b78c928e1a85"
url = "https://github.com/timholy/SnoopCompile.jl.git"

[depot.x86_64-linux.fetchgit.package-TableTraits]
name = "packages/TableTraits/o8VMV"
sha256 = "sha256-hKuGrmcOTiyoV8QyOUt1K7otbC0oKSwckqZyMIxYWiM="
rev = "c06b2f539df1c6efa794486abfb6ed2022561a39"
url = "https://github.com/queryverse/TableTraits.jl.git"

[depot.x86_64-linux.fetchgit.package-PackageCompiler]
name = "packages/PackageCompiler/DKijm"
sha256 = "sha256-gB+ff5DslQbjqIdBht1dXhz+YpVelXAy6OjE0IMjKs0="
rev = "f31ea705915b4e16e8104727ebd99e0c3993478d"
url = "https://github.com/JuliaLang/PackageCompiler.jl.git"

[depot.x86_64-linux.fetchgit.package-Scratch]
name = "packages/Scratch/u24Rl"
sha256 = "sha256-V717glkDqCFnUsj183Q1Ntufd3m2XzP18bvgqTWu7Wg="
rev = "f94f779c94e58bf9ea243e77a37e16d9de9126bd"
url = "https://github.com/JuliaPackaging/Scratch.jl.git"

[depot.x86_64-linux.fetchgit.package-DataAPI]
name = "packages/DataAPI/ILCXt"
sha256 = "sha256-cdgMBrRThYQYJeCysHTtMAO65K/5zKyMOUnMReVtt/Q="
rev = "e08915633fcb3ea83bf9d6126292e5bc5c739922"
url = "https://github.com/JuliaData/DataAPI.jl.git"

[depot.x86_64-linux.fetchgit.package-Comonicon]
name = "packages/Comonicon/1NWD0"
sha256 = "sha256-RJIfJzJUbLXcHZ9hHUTV/nk91j2+tKc8uTX+np8k60U="
rev = "a414f42985134c5e9d59e1c4a63d7b16cd05fd15"
url = "https://github.com/comonicon/Comonicon.jl.git"

[depot.x86_64-linux.fetchgit.package-Configurations]
name = "packages/Configurations/uH65h"
sha256 = "sha256-QboAqmZ1uUBwYjnKqASbDWHVUZC4CDWJ0o+nuUJ0mwE="
rev = "62a7c76dbad02fdfdaa53608104edf760938c4ca"
url = "https://github.com/Roger-luo/Configurations.jl.git"

[depot.x86_64-linux.fetchgit.package-DataStructures]
name = "packages/DataStructures/59MD0"
sha256 = "sha256-D7O8UamRre+kEtHvnqDMnJwdsmXfn5OzBSil0Qh7ecY="
rev = "d1fff3a548102f48987a52a2e0d114fa97d730f0"
url = "https://github.com/JuliaCollections/DataStructures.jl.git"
