name: "CI"
on:
  push:
    branches: [main]
  pull_request:
  # schedule:
  #   - cron: "0 0 * * SUN" # every sunday
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
        with:
          submodules: true
          fetch-depth: 0

      - uses: nixbuild/nix-quick-install-action@v22
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v11
        with:
          name: gtrunsec
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      # - name: Run nsjail Job
      #   run: |
      #     nix -Lv develop .\#tullia --command faketty tullia run julia --runtime nsjail

      # - name: Run podman Job
      #   run: |
      #     nix -Lv develop .\#tullia --command faketty tullia run julia --runtime podman

      # - name: Run podman/docker Dag workflow
      #   run: |
      #     touch $HOME/.netrc
      #     nix -Lv develop .\#tullia --command faketty tullia run jnumpy --runtime podman

      # - name: Run julia with podman/docker
      #   run: nix -Lv run .\#x86_64-linux.julia.entrypoints.podman

      # - name: Build jnumpy with podman/docker
      #   run: nix -Lv run .\#x86_64-linux.julia.entrypoints.jnumpy-podman

      - name: Build Doc
        run: nix develop .#doc --show-trace --refresh --command -- mkdoc

      - name: Build quarto
        run: |
          nix develop .#doc --show-trace --refresh  --command mkQuarto

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: ./docs/publish/public
