name: "CI"
on:
  push:
    branches: [main]
  pull_request:
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v18
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.10.0pre20220728_86fcd4f/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm recursive-nix

      - uses: cachix/cachix-action@v11
        with:
          name: zeek

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Quatro Image
        run: nix -Lv run \#x86_64-linux.quarto.containers.dev.copyToDockerDaemon

      - name: Build/Push the Quarto Docker image
        run: |
          docker run -it -v "$(pwd):/work" --entrypoint /bin/bash ghcr.io/gtrunsec/quarto-dev:latest -c echo hello
          docker push ghcr.io/gtrunsec/quarto-dev:latest
