name: "DockerImages"
on:
  push:
    branches: [main]
  pull_request:
jobs:
  publish-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nixbuild/nix-quick-install-action@v25
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build/Push DataShell Image
        run: |
          nix -LV run .\#x86_64-linux.jupyter.containers.dev.out.copyToRegistry
