name: "DockerImages"
on:
  push:
    branches: [main]
  pull_request:
jobs:
  publish-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - uses: nixbuild/nix-quick-install-action@v22
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v11
        with:
          name: gtrunsec

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build/Push Quatro Image
        run: |
          # docker run -it -v "$(pwd):/work" --entrypoint /bin/bash ghcr.io/gtrunsec/quarto-dev:latest -c echo hello
          nix -Lv develop .\#devShells.x86_64-linux.std --command std //quarto/containers/dev:publish

      - name: Build/Push DataShell Image
        run: |
          nix -Lv develop .\#devShells.x86_64-linux.std --command std //shell/containers/dev:publish
